### ISSUE TITLE
UX Bug, Dragging Scroll Bar on Update Collateral creates User Uncomfort situation

### ISSUE THREAD

**Issue by f0xie7** [script3/yieldblox-beta#153]
Go to https://ybx-beta.script3.io/#/profile
Update the Collateral, Drag the scroll bar out of window makes the windows closed. 
Its better to make window close function rather than this, since dragging it out of window make the last window closed.

Here the ilustration

![ux suggestion](https://user-images.githubusercontent.com/91896561/136473984-077eab30-255b-4ead-b9c6-fc4f10331493.gif)

**Comment by arnob016** [comment]
Upvote 👍
Not only dragging, just clicking anywhere outside the pop-up window (in any section) closes the pop-up. It's kind of annoying. when you set up everything but clicking outside the window closes everything may result in frustration. Suggestion to use a close [✖️/🚫] button instead of 'current situation'. User friendly UIs are always appreciated.

**Comment by f0xie7** [comment]
> 
> 
> Upvote 👍 Not only dragging, just clicking anywhere outside the pop-up window (in any section) closes the pop-up. It's kind of annoying. when you set up everything but clicking outside the window closes everything may result in frustration. Suggestion to use a close [✖️/🚫] button instead of 'current situation'. User friendly UIs are always appreciated.

Clicking outside box is a common situation to close the window, but since its also close the window when u lose the drag outside the box, its probably makes worse user experience.

**Comment by mootz12** [comment]
We have replaced the slider window due to many earlier bugs.
