### ISSUE TITLE
Bug Super Critical. I can Borrow 5M usdc with 21,56K usdc lend

### ISSUE THREAD

**Issue by reigister** [script3/yieldblox-beta#80]
I can borrow 10K usdc with 1.14usdc asset i have lent
![borrow3](https://user-images.githubusercontent.com/78670969/136308327-ec16b532-213a-4a60-a7bc-e0e5d98763e8.png)

**Comment by f0xie7** [comment]
Its the most interesting bug i founded in issues tab recently, is it solved yet? Moreover this bug must be categorized as super critical since if its happen on mainnet, a random people just can grab most of assets available on the platform and run out.

**Comment by mootz12** [comment]
This has been resolved. The underlying issue was there existed a situation in which a specific assets health factor could result in `NaN`.

This threw off our health factor check. Ensuring HF is a real number fixed this issue.

The bug is almost super critical due to the impact, but the scope of the bug is really quite small. The main differentiator between a `Critical` and `Super Critical` bug is the scope of the problem. A `Super Critical` bug requires reworking/redesigning the protocol - and points to a hole in design.

However, this will be awarded on the high side of critical, which is still a large amount of YBX. So thanks for catching and documenting this @reigister

**Comment by reigister** [comment]
thank you very much for the great appreciation. great job sir @mootz12

**Comment by reigister** [comment]
- Discord username : register#1319
